 <div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Dashboard</h1>
    </div>
    <!-- /.col-lg-12 -->
</div>
<div class="row">
    <div class="col-lg-3 col-md-6" id="member">


    </div>

    <div class="col-lg-3 col-md-6" id="service">

    </div>


    <div class="col-lg-3 col-md-6" id="user">

    </div>


    <div class="col-lg-3 col-md-6" id="client">

    </div>
</div>

<script>
<?php $this->inlineScript()->captureStart(); ?>
    $.ajax({
        url: '<?php echo $this->url(array('controller' => 'admin_members', 'action' => 'dashboard'), 'default', true); ?>',
        cache: false

    }).done(function (data) {

        var element = $('#member');

        element.html(data);


    }).fail(function () {
        alert('Unable to load data  for members');
    }).always(function () {

    });

    $.ajax({
        url: '<?php echo $this->url(array('controller' => 'admin_services', 'action' => 'dashboard'), 'default', true); ?>',
        cache: false

    }).done(function (data) {

        var element = $('#service');

        element.html(data);


    }).fail(function () {
        alert('Unable to load data for services');
    }).always(function () {

    });

    $.ajax({
        url: '<?php echo $this->url(array('controller' => 'admin_users', 'action' => 'dashboard'), 'default', true); ?>',
        cache: false

    }).done(function (data) {

        var element = $('#user');

        element.html(data);


    }).fail(function () {
        alert('Unable to load data for users');
    }).always(function () {

    });

    $.ajax({
        url: '<?php echo $this->url(array('controller' => 'admin_clients', 'action' => 'dashboard'), 'default', true); ?>',
        cache: false

    }).done(function (data) {

        var element = $('#client');

        element.html(data);


    }).fail(function () {
        alert('Unable to load data for clients');
    }).always(function () {

    });
<?php $this->inlineScript()->captureEnd(); ?>
</script>