<?php
Zend_Layout::getMvcInstance()->disableLayout();
$activeClients = $this->activeClients;
$totalNumberOfClients = $this->totalNumberOfClients;
?>

<div class="panel panel-red">
    <div class="panel-heading">
        <div class="row">
            <div class="col-xs-3">
                <i class="fa fa-users fa-5x"></i>
            </div>
            <div class="col-xs-9 text-right">
                <div class="huge"><?php echo $this->escape($activeClients . ' / ' .$totalNumberOfClients );?></div>
                <div> active / total</div>
            </div>
        </div>
    </div>
    <a href="<?php echo $this->url(array('controller' => 'admin_clients'), 'default', true);?>">
        <div class="panel-footer">
            <span class="pull-left">View Details-CLIENTS</span>
            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
            <div class="clearfix"></div>
        </div>
    </a>
</div>