
<?php
$this->headTitle('Clients');
?>


<div class="page-header">
    
    <div class="row">
        <div class="col-lg-12">
                <?php echo $this->systemMessagesHtml($this->systemMessages); ?>
        </div>
    </div>
    
    <h1>Clients</h1>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading text-right" >
                <div class="btn-group" role="group" aria-label="...">
                    <button data-action="save-order" 
                            class="btn btn-success" 
                            style="display: none;"><i class="glyphicon glyphicon-save"></i>Save Order</button>
                            
                    <button data-action="toggle-sort" class="btn btn-default" ><i class="glyphicon glyphicon-list"></i>Change Order</button>
                    <a  href="<?php echo $this->url(array('controller' =>'admin_clients', 'action'=>'add'), 'default', true); ?>" type="button" 
                    class="btn btn-default"
                    ><i class="glyphicon glyphicon-plus"></i>Add client</a>
                  
                </div>  
            </div>
            <div class="panel-body">
               
                				<table id="rows-table" class="table table-striped table-hover">
					<thead>
						<tr>
                                                        <th></th>
							<th class="text-center">Img</th>
							<th class="text-center">Status</th>
							<th>Name</th>
							<th>Description</th>
							<th class="text-center">#</th>
						</tr>
					</thead>
					<tbody>
                                            <?php 
                                            foreach ($this->clients as $client) {
                                                if ($client['status'] == Application_Model_DbTable_CmsClients::STATUS_DISABLED){
                                                    ?>
                                                 
                                            <tr data-client-id="<?php echo $this->escape($client['id']);?>" class="danger">
                                                <td class="text-center"><i data-action="sort" class="glyphicon glyphicon-list" style="display: none; cursor:pointer;"></i></td>
							<td class="text-center"><img style="max-height: 24px;" src="<?php echo $this->clientImgUrl($client); ?>"></td>
							<td class="text-center"><span class="badge alert-danger" title="disabled"><i class="glyphicon glyphicon-remove"></i></span></td>
							<td><?php echo $this->escape($client['name']); ?></td>
							<td><?php echo $this->escape($client['description']); ?></td>
							<td class="text-center">
								<div class="btn-group btn-group-sm" role="group" aria-label="...">
                                                                        <a 
                                                                            href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), 'default', true); ?>" 
                                                                            target="_blank"
                                                                            type="button" class="btn btn-default" title="preview"><i class="glyphicon glyphicon-eye-open"></i></a>
									<a 
                                                                            href="<?php echo $this->url(array('controller' => 'admin_clients', 'action' => 'edit', 'id' => $client['id']), 'default', true); ?>" 
                                                                           type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
									<button data-clientName="<?php echo $this->escape($client['name']);?>" data-client-id="<?php echo $this->escape($client['id']);?>" data-action="enable" type="button" class="btn btn-default" title="enable"><i class="glyphicon glyphicon-ok"></i></button>
                                                                        <button data-clientName="<?php echo $this->escape($client['name']);?>" data-client-id="<?php echo $this->escape($client['id']);?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
								</div>
							</td>
						</tr>
                                            <?php
                                                }else{
                                                 
                                                    ?>
                                                    <tr data-client-id="<?php echo $this->escape($client['id']);?>">
                                                        <td class="text-center"><i data-action="sort" class="glyphicon glyphicon-list" style="display: none; cursor:pointer;"></i></td>
                                                        <td class="text-center"><img style="max-height: 24px;" src="<?php echo $this->clientImgUrl($client); ?>"></td>
							<td class="text-center"><span class="badge alert-success" title="enabled"><i class="glyphicon glyphicon-ok"></i></span></td>
							<td><?php echo $this->escape($client['name']); ?></td>
							<td><?php echo $this->escape($client['description']); ?></td>
							<td class="text-center">
								<div class="btn-group btn-group-sm" role="group" aria-label="...">
                                                                        <a 
                                                                            href="<?php echo $this->url(array('controller' => 'index', 'action' => 'index'), 'default', true); ?>" 
                                                                            target="_blank"
                                                                            type="button" class="btn btn-default" title="preview"><i class="glyphicon glyphicon-eye-open"></i></a>
									<a 
                                                                            href="<?php echo $this->url(array('controller' => 'admin_clients', 'action' => 'edit', 'id' => $client['id']), 'default', true); ?>"
                                                                            type="button" class="btn btn-default" title="edit"><i class="glyphicon glyphicon-pencil"></i></a>
									<button data-clientName="<?php echo $this->escape($client['name']);?>" data-client-id="<?php echo $this->escape($client['id']);?>" data-action="disable" type="button" class="btn btn-default" title="disable"><i class="glyphicon glyphicon-remove"></i></button>
                                                                        <button data-clientName="<?php echo $this->escape($client['name']);?>" data-client-id="<?php echo $this->escape($client['id']);?>" data-action="delete" type="button" class="btn btn-default" title="delete"><i class="glyphicon glyphicon-trash"></i></button>
								</div>
							</td>
						</tr>
                                               
                                                    <?php
                                            }
                                            ?> 
                                                
                                                
                                                <?php
                                            }
                                            ?>
                                                
						
					</tbody>
				</table>
              
            </div>
        </div>
    </div>
</div>

<!-- /.modal-content je po defaultu sakriven MODAL DIALOG-->
<form method="post" action="<?php echo $this->url(array('controller'=> 'admin_clients', 'action' => 'delete'), "default", true); ?>" id="delete-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="delete">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Delete client</h4>
      </div>
      <div class="modal-body">
          <p>Are you sure you want to delete client: <span class="osoba" class="btn btn-tumblr"></span></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-trash"></i>Delete</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<!-- /.modal-content je po defaultu sakriven MODAL DIALOG-->
<form method="post" action="<?php echo $this->url(array('controller'=> 'admin_clients', 'action' => 'disable'), "default", true); ?>" id="disable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="disable">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Disable client</h4>
      </div>
      <div class="modal-body">
          <p>Are you sure you want to disable client: <span class="osoba" class="btn btn-tumblr"></span></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-danger"><i class="glyphicon glyphicon-remove"></i>Disable</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->

<!-- /.modal-content je po defaultu sakriven MODAL DIALOG-->
<form method="post" action="<?php echo $this->url(array('controller'=> 'admin_clients', 'action' => 'enable'), "default", true); ?>" id="enable-warning-dialog" class="modal fade" tabindex="-1" role="dialog">
    <input type="hidden" name="task" value="enable">
    <input type="hidden" name="id" value="">
    <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Enable client</h4>
      </div>
      <div class="modal-body">
          <p>Are you sure you want to enable client: <span class="osoba" class="btn btn-tumblr"></span></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-success"><i class="glyphicon glyphicon-ok"></i>Enable</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</form><!-- /.modal -->



<form method="post" action="<?php echo $this->url(array('controller'=> 'admin_clients', 'action' => 'updateorder'), "default", true); ?>" style="display: none;" id="save-order-form">
    
    <input type="hidden" name="task" value="saveOrder">
    <input type="hidden" name="sorted_ids" value="">
    
    
</form>

<?php 
//dodatni css na nasu stranicu
$this->headLink()->appendStylesheet($this->baseUrl('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.css'));

$this->inlineScript()->appendFile($this->baseUrl('/admin/bower_components/jquery-ui-1.12.0/jquery-ui.min.js'));

?>



<script>
<?php $this->inlineScript()->captureStart();?> 
    
    $('#rows-table').on('click', '[data-action="delete"]', function(e){
        e.preventDefault();
        e.stopPropagation();
       
        
        //calculate target element
        var target = $(this).is('[data-action="delete"]') ? $(this) : $(this).closest('[data-action="delete"]');
        
        
        //verzija preko attr fje
        //var memberId = target.attr('data-member-id'); //ovde pun naziv sa data
        
        //verzija preko datat fje
        var clientId =target.data('client-id');//ovde ime bez data
        
        
        //var memberName = target.attr('data-member-id');
        //alert(memberId);
        //set value for input field with name "id"
        
        
        $('#delete-warning-dialog').find('[name="id"]').val(clientId);
       
        $('#delete-warning-dialog').modal('show');
        
        
        var clientData = target.attr('data-clientName');
        $('.osoba').text(clientData);
        
        
    });
    
     $('#rows-table').on('click', '[data-action="disable"]', function(e){
        e.preventDefault();
        e.stopPropagation();
       
        
        //calculate target element
        var target = $(this).is('[data-action="disable"]') ? $(this) : $(this).closest('[data-action="disable"]');
        
        var clientId = target.attr('data-client-id');
        
        //verzija preko datat fje
        //var memberId =target.data('memberId');
        //var memberName = target.attr('data-member-id');
        //alert(memberId);
        //set value for input field with name "id"
        $('#disable-warning-dialog').find('[name="id"]').val(clientId);
       
        $('#disable-warning-dialog').modal('show');
        
         var clientData = target.attr('data-clientName');
        $('.osoba').text(clientData);
        
    });
    
         $('#rows-table').on('click', '[data-action="enable"]', function(e){
        e.preventDefault();
        e.stopPropagation();
       
        
        //calculate target element
        var target = $(this).is('[data-action="enable"]') ? $(this) : $(this).closest('[data-action="enable"]');
        
        var clientId = target.attr('data-client-id');
        
        //verzija preko datat fje
        //var memberId =target.data('memberId');
        //var memberName = target.attr('data-member-id');
        //alert(memberId);
        //set value for input field with name "id"
        $('#enable-warning-dialog').find('[name="id"]').val(clientId);
       
        $('#enable-warning-dialog').modal('show');
        
         var clientData = target.attr('data-clientName');
        $('.osoba').text(clientData);
        
    });
    
    
    
    //SORTIRANJE
    $('[data-action="toggle-sort"]').on('click', function(e){
        
        e.preventDefault();
        e.stopPropagation();
        
       var target = $(this).is('[data-action="toggle-sort"]') ? $(this) : $(this).closest('[data-action="toggle-sort"]');
       
       var sortableTbody =  $('#rows-table > tbody');
       
       
       if(target.hasClass('active')){
           
           
           target.removeClass('active');
           target.html('<i class="glyphicon glyphicon-list"></i> Change Order');
           
          
           
           //destroy sortable functionallity
           sortableTbody.sortable('destroy');
           
           //restore old html body
           sortableTbody.html(sortableTbody.data('oldHtml'));
           
           //hide "handle" for sorting, the icon in first column
           sortableTbody.find('[data-action="sort"]').hide();
           
           
           //hide "Save order"
           $('[data-action="save-order"]').hide();
           
       }else{
           
           target.addClass('active');
           
           //method html sets or gets html inside selected element
           target.html('<i class="glyphicon glyphicon-remove"></i> Cancel');
           
           // save tbody html before sorting under key oldHtml into its data
            sortableTbody.data('oldHtml', sortableTbody.html());
           
           //initialize sortable functionallity
            sortableTbody.sortable({
        
                handle: '[data-action="sort"]'
        
           });
           
           //sow "handle" for sorting, the icon in first column
           sortableTbody.find('[data-action="sort"]').show();
           //show "Save order"
           $('[data-action="save-order"]').show();
       }
              
    });
    
    
    $('[data-action="save-order"]').on('click',function(e) {
    
        e.preventDefault();
        e.stopPropagation();
        
    var clientSortedIds = $('#rows-table > tbody').sortable('toArray', {
        
        attribute: 'data-client-id'
        });
        
        
        
        //select save order form
        var saveOrderForm = $('#save-order-form');
        
        //find element with name "sorted_ids" in save form and set its value
        //with string wich are sorted ids separated with comma
        //ex. "12, 3, 4..."
        saveOrderForm.find('[name="sorted_ids"]').val(clientSortedIds.join(','));
        
       //trigerujemo submit
       saveOrderForm.trigger('submit');
       
        
    });
    
   
    
    
<?php $this->inlineScript()->captureEnd();?> 

</script>