		<?php
$this->headTitle('Services');
?>

<div id="highlighted">
			<div class="container">
				<div class="header">
					<h2 class="page-title">
						<span>Services</span> 
						<small>The services we offer &amp; how we can help you!</small>
					</h2>
				</div>
			</div>
		</div>
		<div id="content">
			<div class="container">
				<!-- Services -->
				<div class="block services">
					<ul class="thumbnails row">
                                             <?php 
                                            foreach ($this->services as $service) {
                                                if ($service['status'] == Application_Model_DbTable_CmsMembers::STATUS_ENABLED){
                                                    ?>
						<li class="col-md-3">
							<h3 class="title">
								<i class="<?php echo $this->escape($service['icon'])?> icon-small icon-inverse-80 _icon-circle"></i><?php echo $this->escape($service['title'])?> 
							</h3>
							<p><?php echo $this->escape($service['description'])?></p>
						</li>
						<?php
                                                }
                            }
                            ?>
					</ul>
					
				</div>
			</div>
		</div>