<?php
//ovde disablujemo layout!!!!
Zend_Layout::getMvcInstance()->disableLayout();
?>



<!DOCTYPE html>
<html>
    <head></head>
    <body>
        <h1>Choose your car brand/model</h1>
        <form action="" method="post">
            <p>
                <label>Brand</label>
                <select id="car-brand">
                    <option value="">--- Choose Brand ---</option>
                </select>
            </p>
            <p>
                <label>Model</label>
                <select id="car-model">
                    <option value="">--- Choose Model ---</option>
                </select>
            </p>
        </form>

        <script src="<?php echo $this->baseUrl('/admin/bower_components/jquery/dist/jquery.min.js'); ?>"></script>

        <script>
            //drugi nacin da se pozove fja
            //$.ajax('/test.html', {});

            //MODEL
            $('#car-brand').on('change', function (e) {

//                e.preventDefault();
//                e.stopPropagation();

                var target = $(this).is('#car-brand') ? $(this) : $(this).closest('#car-brand');


                var brand = target.val();
                var modelSelect = $('#car-model');

                        //clear element onner html
                modelSelect.empty();

                modelSelect.append('<option value="">--- Choose Brand ---</option>');


                if (brand) {
                    $.ajax({
                        url: '/uploads/cars/' + brand + '.json',
                        cache: false

                    }).done(function (data) {
                     

                        for (var index in data) {
                            var model = data[index];

                            var selectOption = $('<option></option>');
                            selectOption.attr('value', model.value);

                            selectOption.html(model.label);

                            modelSelect.append(selectOption);

                        }

                    }).fail(function () {

                        alert('Unable to load models for brand');

                    }).always(function () {

                    });
                }

            });


             //BRAND
            $.ajax({
                url: '<?php echo $this->url(array('controller'=> 'admin_test', 'action' => 'ajaxbrands'), 'default', true); ?>', //ovaj deo se izvrsava na serveru
                cache: false

                        //html,   404/403,  sam ajax zahtev //done se izvrsava smo ako je status 200
            }).done(function (data, textStatus, jqXHR) {
                // on successful ajax page load// ove fj primaju handlers

                for (var index in data) {

                    var brand = data[index];

                    var selectOption = $('<option></option>');//ovde umesto selektora moze da bude i html tag koji cemo naknado da kreiramo

                    selectOption.attr('value', brand.value);
                    selectOption.html(brand.label);

                    $('#car-brand').append(selectOption);

                }


            }).fail(function (jqXHR, textStatus, errorThrown) {
                //on error while loading ajax page
                alert('Error ocured while loading cars brands');

            }).always(function () {
                //for action that do not depend on result

            });


        </script>
    </body>
</html>