<div class="page-header">
  <h1>JavaScript jQuery</h1>
</div>
<div class="row">
	<div class="col-lg-12">
		<button id="ulepsaj-tabelu-btn" class="btn btn-default">Ulepsaj tabelu</button>
		<button data-action="add-row" class="btn btn-default">Dodaj red</button>
		<a data-action="go-to-facebook" href="http://www.facebook.com" class="btn btn-default">Otvori facebook</a>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<table id="test-table">
			<thead>
				<tr>
					<th>ID</th>
					<th>Ime</th>
					<th>Prezime</th>
					<th>#</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td>php01</td>
					<td>Aleksandar</td>
					<td>Stevanovic</td>
					<td>
						<div class="btn-group">
							<button class="btn btn-sm"><i class="fa fa-eye"></i></button>
							<button data-action="delete-row" class="btn btn-sm"><i class="fa fa-trash"></i></button>
						</div>
					</td>
				</tr>
				<tr>
					<td>php02</td>
					<td>Natasa</td>
					<td>Lukic</td>
					<td>
						<div class="btn-group">
							<button class="btn btn-sm"><i class="fa fa-eye"></i></button>
							<button data-action="delete-row"  class="btn btn-sm"><i class="fa fa-trash"></i></button>
						</div>
					</td>
				</tr>
				<tr>
					<td>php03</td>
					<td>Aleksandra</td>
					<td>Petkovic</td>
					<td>
						<div class="btn-group">
							<button class="btn btn-sm"><i class="fa fa-eye"></i></button>
							<button data-action="delete-row"  class="btn btn-sm"><i class="fa fa-trash"></i></button>
						</div>
					</td>
				</tr>
				<tr>
					<td>php04</td>
					<td>Djordje</td>
					<td>Stojiljkovic</td>
					<td>
						<div class="btn-group">
							<button class="btn btn-sm"><i class="fa fa-eye"></i></button>
							<button data-action="delete-row"  class="btn btn-sm"><i class="fa fa-trash"></i></button>
						</div>
					</td>
				</tr>
				<tr>
					<td>php05</td>
					<td>Milos</td>
					<td>Stefanovic</td>
					<td>
						<div class="btn-group">
							<button class="btn btn-sm"><i class="fa fa-eye"></i></button>
							<button data-action="delete-row"  class="btn btn-sm"><i class="fa fa-trash"></i></button>
						</div>
					</td>
				</tr>
				<tr>
					<td>php06</td>
					<td>Milomir</td>
					<td>Dragovic</td>
					<td>
						<div class="btn-group">
							<button class="btn btn-sm"><i class="fa fa-eye"></i></button>
							<button data-action="delete-row"  class="btn btn-sm"><i class="fa fa-trash"></i></button>
						</div>
					</td>
				</tr>
				<tr>
					<td>php07</td>
					<td>Miroslav</td>
					<td>Mutic</td>
					<td>
						<div class="btn-group">
							<button class="btn btn-sm"><i class="fa fa-eye"></i></button>
							<button data-action="delete-row"  class="btn btn-sm"><i class="fa fa-trash"></i></button>
						</div>
					</td>
				</tr>
				<tr>
					<td>php08</td>
					<td>Bojan</td>
					<td>Joncic</td>
					<td>
						<div class="btn-group">
							<button class="btn btn-sm"><i class="fa fa-eye"></i></button>
							<button data-action="delete-row"  class="btn btn-sm"><i class="fa fa-trash"></i></button>
						</div>
					</td>
				</tr>
				<tr>
					<td>php09</td>
					<td>Arben</td>
					<td>Bakiu</td>
					<td>
						<div class="btn-group">
							<button class="btn btn-sm"><i class="fa fa-eye"></i></button>
							<button data-action="delete-row"  class="btn btn-sm"><i class="fa fa-trash"></i></button>
						</div>
					</td>
				</tr>
				<tr>
					<td>php10</td>
					<td>Zeljka</td>
					<td>Babic</td>
					<td>
						<div class="btn-group">
							<button class="btn btn-sm"><i class="fa fa-eye"></i></button>
							<button data-action="delete-row" class="btn btn-sm"><i class="fa fa-trash"></i></button>
						</div>
					</td>
				</tr>
			</tbody>
		</table>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<button id="ulepsaj-tabelu-btn2" class="btn btn-default">Ulepsaj tabelu</button>
		<button data-action="add-row" class="btn btn-default">Dodaj red</button>
		<a data-action="go-to-facebook" href="http://www.facebook.com" class="btn btn-default">Otvori facebook</a>
	</div>
</div>
<script>
<?php $this->inlineScript()->captureStart();?>
    //ova f-ja vraca jquery objekat, svaki element koji ima table tag :)
    //i dodaje table
    
    /*var testTable = $('#test-table')
    
    testTable.addClass('table')
            .addClass('table-striped')
            .addClass('table-hover');
    
    
    //nasli smo element sa ovim id-jem #test-table unutar tbody tr
    testTable.find('tbody tr').addClass('danger');
    //$('#test-table tbody tr').addClass('danger');
    
   //traversing, setanje kroz DOM, za selektovanje roditelja i child-ova
    //testTable.parent().parent()
    
    var firstRow = testTable.find('tbody tr').first();
    
    var firstRowClone = firstRow.clone();
    
    testTable.find('tbody').append(firstRowClone);  */
    
    
    //f-ja on dodaje event handling
    $('#ulepsaj-tabelu-btn').on('click', function(e){
        $('#test-table').addClass('table table-striped table-hover');
    });
    
    //selektor po atributu
    $('[data-action="add-row"]').on('click', function(e) {
       //selektovali last row i klonirali
       var lastRowClone = $('#test-table tbody tr:last').clone();
       
       
       lastRowClone.addClass('success');
       
       //dodajemo ga na tbody
       $('#test-table tbody').append(lastRowClone);
       
    });
    
    //selektovanje po atributu
    $('[data-action="go-to-facebook"]').on('click', function(e) {
        //sprecava difolnto ponasanje
        e.preventDefault(); //prevents default event handler on element
        //ex. prevents a element to load another page on click
        
        
        //citamo href atribut
        // ovako selektujemo obekat nad kojim se izvrsio element $(this)
        //attr f-ja odnosno metoda da procitamo ili setujemo element od nekog atributa
        var url = $(this).attr('href');
        
        alert('Browser is prevented to go to url: ' + url);
        
    });
    
//    $('[data-action="delete-row"]').on('click', function(e){
//        
//        e.preventDefault();
//        //element that was clicked
//        var target = $(this);
//        
//       //button  div      td      tr
//        //target.parent().parent().parent();
//        
//        var closestTableRow = target.closest('tr'); //najblizi roditelj koji ima ime tr
//        //delete closest table row
//        var closestTableRow = target.closest('tr');
//        
//    });

   $('#test-table').on('click', '[data-action="delete-row"]', function(e){
    
  
    e.preventDefault();
    //stop event bubbling 
    e.stopPropagation();
    
    var target = $(this);
    var closestTableRow = target.closest('tr');
    closestTableRow.remove();
    
});
    
    
    
<?php $this->inlineScript()->captureEnd();?>    
</script>
