                                                                                                                

<div class="page-header">
  <h1>JavaScript 1</h1>
</div>


<script>
    <?php $this->inlineScript()->captureStart(); ?>
    
var ime = 'Ime1';
var starost = 30;

//alert(ime);

var polaznici = ['Aleksandar Stevanovic', 'Natasa Lukic', 'Aleksandra Petkovic'];

for(var index in polaznici){
    //console.log(index + ': ' + polaznici[index]);
}


//console.log(polaznici);
//parseInt(index)+1
//alert(polaznici[1]);


//pravimo asocijativni niz
var polaznik = {
    ime: 'Ime1', 
    prezime: 'Prezime1',
    starost: 30
};


for(var key in polaznik){
    //console.log(key + '-> ' + polaznik[key]);
}

//alert(polaznik.prezime);

//JSON - JavaScript Object Notation

var cubes = {
    name: 'Cubes d.o.o',
    address: 'Bul Mihajla pupina 181',
    courses: [
        {
            name: 'PHP',
            students: {
                php01: 'Aleksandar Stevanovic',
                php02: 'Natasa Lukic',
                php03: 'Aleksandra Petkovic'
            }
        },
        
        {
            name: 'IOS',
            students: {
                ios01: 'IOS 1',
                ios02: 'IOS 2',
                ios03: 'IOS 3'
            }
        }              
    ]
};
                        
   window.c                                                                                                                                                                           
//console.log(cubes);

//alert(cubes.courses[0].students.php03);

//alert(cubes['courses'][0]['students']['php02']);


var doubleTestNubmer = 77;
//pozivanje fje 1
function testF(testNumber) {
    var doubleTestNubmer  = testNumber *2; //ukoliko nije ovde definisana trazi se van 
    //console.log('Calling finction testF ' + doubleTestNubmer+ '!');
    
}; //stavljati ;

testF(1);//pozivanje fje
testF(2);
testF(3);
testF(4);
testF(5);
//console.log('Double Test nuber is ' + doubleTestNubmer);


//pozivanje funkcije nacin 2
var testF2 = function(){ //ANONIMNA FUNKCIJA-NEMA IME
    console.log('Caling testF2!');
};


testF2();
//instanciranje objekat uz pomic fje
//Object constructor
function Polaznik(ime, prezime, starost){
    
    this.ime = ime;
    this.prezime = prezime;
    this.starost = starost;
    
    this.predstaviSe = function() {
        return 'Ja sam ' + this.ime + ' ' + this.prezime + ' i imam ' + this.starost + 'god';
    
};
};

var p1 = new Polaznik('Ime1', 'Prezime1', '11');
var p2 = new Polaznik('Ime2', 'Prezime2', '22');
var p3 = new Polaznik('Ime3', 'Prezime3', '33');
var p4 = new Polaznik('Ime4', 'Prezime4', '44');

console.log(p1.predstaviSe());
console.log(p2.predstaviSe());
console.log(p3.predstaviSe());
console.log(p4.predstaviSe());

p4.getIme = function(){ //naknado je dodat property samo za p4 i samo ce on ima ti njega
    return this.ime;
};





//master objekat
//ako se ne navede var podrazumeva se da je window objekat
window;

//working with computer screen
window.screen;
screen;

//working with browser location (adress bar)
window.location;
location;

//setTimeout(function(){
//    
//    location.href = "http://www.google.com/"; //redirect
//    
//}, 5000);//nakon 5sc izvrsi ovu fju


//DOM
window.document


<?php $this->inlineScript()->captureEnd(); ?>
</script>



 

