<div class="page-header">
  <h1>SOAP Web Servisi</h1>
</div>

<div class="row">
    <div class="col-xs-12">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Valuta</th>
                    <th>Prodajni kurs</th>
                    <th>Kupovni kurs</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->currencyList as $currency) {?>
                <tr>
                    <td><?php echo $this->escape($currency->CurrencyNameSerLat)?></td>
                    <td><?php echo $this->escape($currency->SellingRate)?></td>
                    <td><?php echo $this->escape($currency->BuyingRate)?></td>
                    
                </tr>
                <?php }?>
            </tbody>
            
        </table>
    </div>
</div>

<div class="alert alert-danger">
    <?php echo $this->escape($this->error);?>
</div>


<pre>
<?php echo  $this->escape(print_r($this->response, TRUE)); ?>
</pre>
