<?php
Zend_Layout::getMvcInstance()->disableLayout();
$activeUsers = $this->activeUsers;
$totalNumberOfUsers = $this->totalNumberOfUsers;
?>

<div class="panel panel-yellow">
    <div class="panel-heading">
        <div class="row">
            <div class="col-xs-3">
                <i class="fa fa-user fa-5x"></i>
            </div>
            <div class="col-xs-9 text-right">
                <div class="huge"><?php echo $this->escape($activeUsers . ' / ' .$totalNumberOfUsers );?></div>
                <div>active / total</div>
            </div>
        </div>
    </div>
    <a href="<?php echo $this->url(array('controller' => 'admin_users'), 'default', true);?>">
        <div class="panel-footer">
            <span class="pull-left">View Details-USERS</span>
            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
            <div class="clearfix"></div>
        </div>
    </a>
</di/div>