<?php
$this->headTitle('Contacts');

$form = $this->form;
$form->setElementDecorators(array('ViewHelper'));
$systemMessages = $this->systemMessages;
?>


<div id="highlighted">
			<div class="container">
				<div class="header">
					<h2 class="page-title">
						<span>Contact</span> 
						<small>No project too big or small, get in touch!</small>
					</h2>
				</div>
			</div>
		</div>
		<div id="content">
			<div class="container">
				<div class="block">
					<div class="row">
						<div class="col-sm-6">
                                                    <?php if ($systemMessages == 'init') { ?>
                                                    
                                                          <form action="" method="POST" id="contact-form">
                                                            <input type="hidden" name="task" value="contact">
                                                            <div class="form-group">
                                                                <?php
                                                                echo $form->getElement('name')->setAttribs(array(
                                                                    'class' => 'form-control input-md',
                                                                    'placeholder' => "enter your name",
                                                                    'id' => 'name',
                                                                    'required' => 'required'
                                                                ));
                                                                ?>
								</div>
                                                            <div class="col-md-4">
                                                                    <?php if ($form->getElement('name')->hasErrors()) { ?>
                                                                        <div class="has-error">
                                                                            <?php foreach ($form->getElement('name')->getMessages() as $message) { ?>
                                                                                <p class="help-block"><?php echo $this->escape($message); ?></p>
                                                                            <?php } ?>
                                                                        </div>
                                                                    <?php } ?>
                                                                </div>
                                                            
                                                            
                                                            
                                                            
								<div class="form-group">
								<?php
                                                                echo $form->getElement('email')->setAttribs(array(
                                                                    'class' => 'form-control input-md',
                                                                    'placeholder' => "enter your email",
                                                                    'id' => 'email',
                                                                    'required' => 'required'
                                                                ));
                                                                ?>
								</div>
                                                            
                                                               
                                                                <div class="col-md-4">
                                                                    <?php if ($form->getElement('email')->hasErrors()) { ?>
                                                                        <div class="has-error">
                                                                            <?php foreach ($form->getElement('email')->getMessages() as $message) { ?>
                                                                                <p class="help-block"><?php echo $this->escape($message); ?></p>
                                                                            <?php } ?>
                                                                        </div>
                                                                    <?php } ?>
                                                                </div>
                                                            
                                                            
								<div class="form-group">
								<?php
                                                                echo $form->getElement('message')->setAttribs(array(
                                                                    'class' => 'form-control input-md',
                                                                    'placeholder' => "enter your email",
                                                                    'id' => 'message',
                                                                    'required' => 'required',
                                                                    'rows' => 15
                                                                ));
                                                                ?>
								</div>
                                                                  <div class="col-md-4">
                                                                    <?php if ($form->getElement('message')->hasErrors()) { ?>
                                                                        <div class="has-error">
                                                                            <?php foreach ($form->getElement('message')->getMessages() as $message) { ?>
                                                                                <p class="help-block"><?php echo $this->escape($message); ?></p>
                                                                            <?php } ?>
                                                                        </div>
                                                                    <?php } ?>
                                                                </div>
                                                            
                                                            
								<input type="submit" value="Send Message" class="btn btn-primary">
							</form>
                                                    <?php
                                                    } else {
                                                        if ($systemMessages == 'Success'){
                                                            echo 'Uspesno poslata poruka';
                                                        } else {
                                                            echo "Doslo je do greske prilikom slanja poruke.";
                                                        }
                                                    }
                                                    ?>
                                                  
						</div>
						<div class="col-sm-6">
							<h3 class="block-title sub-title">
								<span>Other Ways To Get In Touch</span>
							</h3>
							<p><abbr title="Phone">P</abbr>: 011/3210-112</p>
							<p><abbr title="Fax">F</abbr>: 011/3210-112</p>
							<p><abbr title="Email">E</abbr>: office@cubes.rs</p>
							<p><abbr title="Address">A</abbr>: Bulevar Milutina Milankovića 181, 11000 Beograd</p>
							<a href="https://maps.google.co.uk/maps?q=London&amp;ie=UTF8&amp;hq=&amp;hnear=London,+United+Kingdom&amp;gl=uk&amp;t=m&amp;ll=51.510238,-0.127029&amp;spn=0.042735,0.102654&amp;z=12&amp;">
								<img class="img-polaroid" alt="Location map" src="/img/misc/map.png">
							</a>
						</div>
					</div>
				</div>
			</div>
		</div>